Issue 46: Add Hashicorp Vault to the All-in-one management hub
open-horizon/devops pull request #85
Opened 2021-09-15 18:27 UTC by naphelps

References: #46
Depends on: https://github.com/open-horizon/vault-exchange-auth/pull/29

Changes:
- Adds Vault service to Docker environment.
- Adds Vault config option to `agbot-tmpl.json`
- Adds Vault instance setup and configuration to `deploy-mgmt-hub.sh`
- Adds `vault-tmpl.json` for base Vault configuration.

Does not support HTTPS at this time.

2021-09-16 17:02 UTC, bmpotter requested changes

2021-09-17 14:17 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +export VAULT_DEV_LISTEN_ADDRESS=${VAULT_DEV_LISTEN_ADDRESS:-0.0.0.0:${VAULT_PORT}}
This is for vault inside the container. `VAULT_DEV_LISTEN_ADDRESS` is needed for the docker image.

2021-09-17 14:24 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +VAULT_KEYS_FILE=$VAULT_KEYS_DIR/keys.json
It does. Line 732: `rm -dfr ${ETC}/vault`

2021-09-17 14:25 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +if [[ ! -d ${VAULT_KEYS_DIR} ]]; then
Fixed.

2021-09-17 14:29 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +vaultAuthMethodCheck() {
Fixed.

2021-09-17 14:33 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +        jq -a $VAULT_ROOT_TOKEN '.root_token=$VAULT_ROOT_TOKEN' < $VAULT_KEYS_FILE > $VAULT_KEYS_FILE
Made these into a todo for the time being. Attempted to regenerate the root token and vault rejected the new token I was given.

2021-09-17 14:43 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +    docker-compose exec -e VAULT_TOKEN=$VAULT_ROOT_TOKEN vault vault write -address=$HZN_TRANSPORT://0.0.0.0:8200 auth/openhorizon/config url=$HZN_TRANSPORT://exchange-api:8080/v1 token=$VAULT_ROOT_T
Fixed.

2021-09-17 15:26 UTC, naphelps commented on mgmt-hub/deploy-mgmt-hub.sh
> +export VAULT_INSTANCE_DIR=${ETC}/vault/file  # Persistent volume for Vault instance
Fixed.

2021-09-22 11:17 UTC, bmpotter commented on mgmt-hub/deploy-mgmt-hub.sh
> +export VAULT_DEV_LISTEN_ADDRESS=${VAULT_DEV_LISTEN_ADDRESS:-0.0.0.0:${VAULT_PORT}}
But it is also used in the `ports` section in `docker-compose.yml`, which means it is exposing that port to the host with the IP in `VAULT_DEV_LISTEN_ADDRESS`, not the IP in `HZN_LISTEN_IP`

2021-09-22 11:27 UTC, bmpotter commented on mgmt-hub/deploy-mgmt-hub.sh
> +VAULT_KEYS_FILE=$VAULT_KEYS_DIR/keys.json
It looks like you commented out all of the lines that create and remove this file, but `vaultInitialize` still tries to use it.

2021-09-23 18:37 UTC, bmpotter approved these changes

2021-09-23 18:38 UTC, merged